### ISSUE TITLE
Some tooltips don't display

### ISSUE THREAD

**Issue by ramnathv** [DarkMarmot/kodama#10]
See [here](http://jsfiddle.net/ramnathv/wjjvkaur/). Try hovering on any of the points on the top left of the plot. Adding the following css fixes the bug. Basically, it prevents the tooltip div from hijacking pointer events, which prevent the svg nodes underneath from receiving the hover events.

``` css
div[name="kodama"]{
   pointer-events: none;
}
```

Instead of `name`, I would recommend using a `class` attribute.
